name: AWS Bedrock Code Review Action
description: 'A Code Review Action Using AWS Bedrock'
inputs:
    # AWS
    aws-access-key-id:
        description: 'AWS Access Key ID'
        required: true
    aws-secret-access-key:
        description: 'AWS Secret Access Key'
        required: true
    aws-region:
        description: 'AWS Region'
        required: true
    # GitHub
    github-token:
        description: 'GitHub Token'
        required: true
    # Bedrock
    anthropic-model:
        description: 'Bedrock Anthropic Model Id'
        required: false
        default: 'anthropic.claude-3-haiku-20240307-v1:0'
    max-tokens:
        description: 'Max Tokens'
        required: false
        default: 1000

branding:
  icon: 'check-circle'
  color: white

runs:
  using: 'composite'
  steps:
    - run: pip install botocore
      shell: bash
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      env:
        INPUT_AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        INPUT_AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        INPUT_AWS_REGION: ${{ inputs.aws-region }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
        INPUT_ANTHROPIC_MODEL: ${{ inputs.anthropic-model }}
        INPUT_MAX_TOKENS: ${{ inputs.max-tokens }}